logfilename: "textfile.txt"
filename: "bank-additional-full.csv"
delimiter: ';'
columns:
    - age
    - job
    - marital
    - education
    - default
    - housing
    - loan
    - contact
    - month
    - day_of_week
    - duration
    - campaign
    - pdays
    - previous
    - poutcome
    - emp.var.rate
    - cons.price.idx
    - cons.conf.idx
    - euribor3m
    - nr.employed
    - y

# Define lists
models: []
names: []
results: []
basicscore: []
n_estimators: 50
